### ISSUE TITLE
Groups and referance

### ISSUE THREAD

**Issue by benefron** [SpikeInterface/spiketoolkit#288]
Hello,
I uploaded a probe file but I want to change the groups and reference the groups.
I do it but then it is empty.
What is the syntex for grouping and reference grouping
Thank you
Ben

**Comment by alejoe91** [comment]
Hi Ben,

Can you paste the code you are using? What is empty? Also how do you want to change reference? Using other channels or using a common reference?

**Comment by benefron** [comment]
g = g = [1,2,1,1,1,1,2,2,1,1,1,1,1,1,2,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3]

recording_prb.set_channel_groups(channel_ids,g)

recording_f = st.preprocessing.bandpass_filter(recording_prb, freq_min=300, freq_max=6000)
recording_rm_noise = st.preprocessing.remove_bad_channels(recording_f, bad_channel_ids=[])
recording_cmr = st.preprocessing.common_reference(recording_rm_noise,reference='single',groups=[1,2,3],ref_channels=[13,27,6]) 
When I try to run the last line it returns an error

**Comment by benefron** [comment]
also when I try to  plot
sw.plot_timeseries(recording_cmr, channel_ids=[0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,27,28,29,30,31])
the plot is empty

**Comment by alejoe91** [comment]
Hi @benefron 

You can skip the `st.preprocessing.remove_bad_channels` as you are not removing any channels (that's optional).

The way `groups` work in `st.preprocessing.common_reference``is that you have to pass a list of lists with the channel ids of each group manually. I think though that what you are suggesting is a good way to do it in case one wants to use the channel groups as reference groups. 

So you'll need something like:
`recording_cmr = st.preprocessing.common_reference(recording_f,reference='single',groups=[[0,2,3,4,5,8,9,11,12,13,15], [1,6,7,14], [16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]],ref_channels=[13,27,6])`

This will rereference the first list of channels to 13, the second to 27, and the third to 6. 
Is this your intended behavior?

**Comment by benefron** [comment]
I tried it the way you suggested and again when I try to create snippets or plot the common reference trace I get:

  "File "C:\ProgramData\Anaconda3\lib\site-packages\spiketoolkit\preprocessing\filterrecording.py", line 42, in get_traces
    filtered_chunk = np.zeros((len(channel_ids), (end_frame-start_frame)), dtype=dt)
TypeError: object of type 'int' has no len()"


I try to run this two codes on it:
"trace_cmr_snippet = recording_cmr.get_traces(channel_ids = channel_ids,start_frame = int(0*fs), end_frame = int(30*fs))
sw.plot_timeseries(recording_cmr, channel_ids=[21,22,23,24,29,30,31])"

when I just do median reference with no groups it works

**Comment by alejoe91** [comment]
@benefron that was indeed a bug! Thanks for spotting it. I fixed it here: https://github.com/SpikeInterface/spiketoolkit/pull/289
I'll merge it soon.

Do you know how to install spiketoolkit from github? That will fix your issue

**Comment by benefron** [comment]
git clone https://github.com/SpikeInterface/spiketoolkit.git
cd spiketoolkit
python setup.py install
I ran this and now it works

**Comment by alejoe91** [comment]
Great! Also notice that in your code the ref_channels are reversed! It should be `ref_channels=[13,6,27]` instead of `ref_channels=[13,27,6]`.

I'll close this issue

**Comment by benefron** [comment]
Sorry i ran it with median instead of single
with single it still doesn't work

**Comment by benefron** [comment]
Hi I couldn't answer in the issue.
i made a mistake and ran the code with median and not single.
I still get the same problem as before.

**Comment by alejoe91** [comment]
Hi, can you try to `git pull` and reinstall? 
I merged to master now so it should work! Let me know

**Comment by benefron** [comment]
Sorry for the question
how do I ran git pull?

**Comment by alejoe91** [comment]
You go from a terminal in the spiketoolkit folder, then you run:
git pull
python setup.py install

**Comment by benefron** [comment]
Updated and restarted spyder and still the same error

TypeError: object of type 'int' has no len()

**Comment by alejoe91** [comment]
Can you try to run pip uninstall spiketoolkit before python setup.py install?

It works on my side with the latest commit

**Comment by benefron** [comment]
It works now but when I run:
sw.plot_timeseries(recording_cmr, channel_ids= [16])
I get the following:

  File "C:\ProgramData\Anaconda3\lib\site-packages\spikewidgets\widgets\timeserieswidget\timeserieswidget.py", line 136, in _initialize_stats
    self._channel_stats[self._visible_channels[ii]] = _compute_channel_stats_from_data(chunk0[ii, :])

IndexError: list index out of range

**Comment by benefron** [comment]
It is working now perfectly,
Thank you
Ben 
I am closing the issue
