### ISSUE TITLE
export_to_phy fails

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#454]
[Edit, what I previously said was wrong]

Hi,

I'm used to running `export_to_phy` using a `BinDatRecording`, which deletes my channels positions.
So I tried loading the `prb` file using `ecording = recording.load_probe_file(params0['prb'])`, but when I do that, `phy` cannot read the output folder:

```
12:57:14.544 [E] __init__:62          An error has occurred (AssertionError): 
Traceback (most recent call last):
  File "/users/nsr/wyngaard/.conda/envs/phy/bin/phy", line 8, in <module>
    sys.exit(phycli())
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phy/apps/__init__.py", line 159, in cli_template_gui
    template_gui(params_path, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phy/apps/template/gui.py", line 198, in template_gui
    controller = TemplateController(model=load_model(params_path), dir_path=dir_path, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phylib/io/model.py", line 1178, in load_model
    return TemplateModel(**get_template_params(params_path))
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phylib/io/model.py", line 297, in __init__
    self._load_data()
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phylib/io/model.py", line 316, in _load_data
    assert self.amplitudes.shape == (ns,)
AssertionError

```

Here is the line used to produce this error:
```
spiketoolkit.postprocessing.export_to_phy(data.recording, data.merged_sorting, params0['path'], compute_pc_features=True, compute_amplitudes=True, max_channels_per_template=64, copy_binary=False, ms_before=1.0, ms_after=3.0, dtype=np.int16, recompute_info=False)
```

**Comment by alejoe91** [comment]
Hi, 

The first issue is fixed here (https://github.com/SpikeInterface/spiketoolkit/commit/61f9231cbdc9521a46acca6428ce25e1bab5288c - accidentally pushed to master).

I can't replicate the second issue unfortunately. Can you paste some minimal code using the toy_example that fails?

**Comment by Dradeliomecus** [comment]
I edited my post, turns out it didn't come from `compute_pc_features` but from the loaded prb file (sorry :/)

**Comment by alejoe91** [comment]
no worries! Can we close it?

**Comment by Dradeliomecus** [comment]
I've updated my `spikeinterface` packages, and I'm trying multiple things to see if I can reproduce the error (and if yes, where it really comes from).

If I can't reproduce it, I'll close the issue!

**Comment by Dradeliomecus** [comment]
Actually the previous statement I made was true.
Switching from:
```
spiketoolkit.postprocessing.export_to_phy(data.recording, data.merged_sorting, params0['path'], compute_pc_features=False, compute_amplitudes=False, max_channels_per_template=64, copy_binary=False, ms_before=1.0, ms_after=3.0, dtype=np.int16, recompute_info=False)
```

To:
```
spiketoolkit.postprocessing.export_to_phy(data.recording, data.merged_sorting, params0['path'], compute_pc_features=False, compute_amplitudes=True, max_channels_per_template=64, copy_binary=False, ms_before=1.0, ms_after=3.0, dtype=np.int16, recompute_info=False)
```

Produced an error.
The first line worked, and with the second line, using `phy template-gui params.py` produced the following error:
```
14:26:59.640 [E] __init__:62          An error has occurred (AssertionError): 
Traceback (most recent call last):
  File "/users/nsr/wyngaard/.conda/envs/phy/bin/phy", line 8, in <module>
    sys.exit(phycli())
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phy/apps/__init__.py", line 159, in cli_template_gui
    template_gui(params_path, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phy/apps/template/gui.py", line 198, in template_gui
    controller = TemplateController(model=load_model(params_path), dir_path=dir_path, **kwargs)
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phylib/io/model.py", line 1178, in load_model
    return TemplateModel(**get_template_params(params_path))
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phylib/io/model.py", line 297, in __init__
    self._load_data()
  File "/users/nsr/wyngaard/.conda/envs/phy/lib/python3.7/site-packages/phylib/io/model.py", line 316, in _load_data
    assert self.amplitudes.shape == (ns,)
AssertionError
```

**Comment by alejoe91** [comment]
Unfortunately I can't reproduce the error using the example dataset...

**Comment by Dradeliomecus** [comment]
My code preceding the `export_to_phy` is pretty heavy ...

How can I debug to see where things go wrong?

**Comment by alejoe91** [comment]
it seems that somehow the amplitudes have the wrong shapes..or maybe I'm missing something... can you try to replicate the issue using `rec, sort = se.example_datasets.toy_example()`? Maybe it's a matter of multiple recalculations of amplitudes..

**Comment by Dradeliomecus** [comment]
This worked:

```
import numpy as np
import spikeextractors
import spiketoolkit

recording, sorting = spikeextractors.example_datasets.toy_example()
spiketoolkit.postprocessing.export_to_phy(recording, sorting, "/users/nsr/wyngaard/Documents/tmp/output", compute_pc_features=False, compute_amplitudes=True, max_channels_per_template=4, copy_binary=False, ms_before=1.0, ms_after=3.0, dtype=np.int16, recompute_info=False)
```

**Comment by alejoe91** [comment]
running that on my side and I got no problem in opening phy..maybe it's a different phy version?

**Comment by Dradeliomecus** [comment]
I'm using the latest version of  `phy`.

I also tried to set `recompute_info=True` (since I'm changing the number of spikes in some units), but I still have the same error message when opening `phy`.

**Comment by alejoe91** [comment]
Thes ones: 
```
phy                           2.0b1
phylib                        2.2
```
??

**Comment by Dradeliomecus** [comment]
```
phy                       2.0b1                    pypi_0    pypi
phylib                    2.2                      pypi_0    pypi
```

I successfully can open the folder created with the test dataset, but not the one made with my complex algorithm ...

**Comment by Dradeliomecus** [comment]
My `sorting` object is a `NumpySortingExtractor` where I inject the units with their spike train one by one.

Could this be causing this issue?

**Comment by alejoe91** [comment]
Can you try to inject the units all at once? How do you inject them one by one?

**Comment by Dradeliomecus** [comment]
I am using (in a loop):
```
data.merged_sorting.add_unit(len(data.merged_sorting.get_unit_ids()), spike_train[i])
```

**Comment by Dradeliomecus** [comment]
I opened `amplitudes.npy` and `spike_times.npy`, and their shape are respectively `(6300, 1)` and `(59539, 1)`.

Is this normal?

**Comment by alejoe91** [comment]
No, they should be the same! That's a good hint. I'll take a look

**Comment by alejoe91** [comment]
Can you try this: https://github.com/SpikeInterface/spiketoolkit/pull/457 ?

**Comment by Dradeliomecus** [comment]
It didn't fix the issue.

I tried this on a different dataset, and now the shape of both npy are `(9900, 1)` and `(1032173, 1)`.

On the first data set, I had 21 units. On this one, I have 33.
6300 / 21 = 9900 / 33 = 300.

Is there a cap at 300 with the `NumpySortingExtractor`?

**Comment by alejoe91** [comment]
No, there shouldn't. By default 300 waveforms are extracted, but it should not be the case in the `export_to_phy`. The problem here is that you probably already compute the amplitudes before (by default on 300 spikes) and they are not recomputed. The patch I pushed should check if there is a mismatch between the available and requested amplitudes and recompute them in case there is.

Can you try to run it again after deleting the phy folder (and pushing the latest commit)?

**Comment by Dradeliomecus** [comment]
I deleted the phy folder, then did:
```
git checkout phy_compute_amps
git pull
sudo python3 setup.py install // Fails without sudo.
```

Then reran my code twice, and the same problem is there ...

**Comment by alejoe91** [comment]
What do you get when you do: `sorting.get_shared_unit_spike_feature_names()`? (where `sorting` would be your sorting extractor)

Maybe you have amplitudes computed for some of the units and that doesn't trigger recomputation..for now, I'd force `reocmpute_info=True` to be sure. Then I'd probably need to take a looka t your data + your complex code to build the sorting extractor.

**Comment by Dradeliomecus** [comment]
`recompute_info` is set to `True` (this is why I find it so weird).

Maybe I can try to pickle my `recording` and `sorting` objects and send it to you?

I'll send you the result of `sorting.get_shared_unit_spike_feature_names()` once my code finished running.

**Comment by Dradeliomecus** [comment]
```
print(data.merged_sorting.get_shared_unit_spike_feature_names())
['amplitudes', 'amplitudes_idxs', 'waveforms', 'waveforms_idxs']
```

Phy still fails to open (even after the latest pull 10 minutes ago).

**Comment by alejoe91** [comment]
Yeah this is indeed a problem. Since the waveforms and amplitues should be computed on all spikes, the `_idxs` features, which tell you which spikes have been used to compute features, should not be there..

The error is happening around these lines in my opinion: https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L1584-L1653

Maybe you can try to raise some Exception and see where the dimensions start to get weird!

**Comment by Dradeliomecus** [comment]
I just ran the same code, but adding `max_spikes_per_unit=None, max_spikes_for_amplitudes=None` to the `export_to_phy` method.

Now, it takes a **lot** longer to export (from 4s to 1050s)

Now `phy` opens correctly!
I guess these variables should be `None` by default?

Also, is it normal that it takes this long on an ssd? (I set `compute_pc_features` to `False` in the hope of saving some time).

**Comment by Dradeliomecus** [comment]
By the way, setting `max_spikes_per_unit=None, max_spikes_for_amplitudes=None` also solves a previous issue of mine (#439).

**Comment by alejoe91** [comment]
Ahhh! I guess that's it! I do set the `max_spikes_per_unit=None`, but not the `max_spikes_for_amplitudes=None`

Good catch! It is normal it takes so long. To comput amplitudes for all spikes, it needs to access the raw data many many times..If you have `compute_amplitudes=True`, you can also compute pc features as the most time consuming part is retrieving waveforms, whihc is done in both cases

**Comment by alejoe91** [comment]
Can you try with the latest commit of the PR, without setting `max_spikes_per_unit` and `max_spikes_for_amplitudes`?

**Comment by Dradeliomecus** [comment]
Yep it works!

Thank you :)
